### ISSUE TITLE
Große katastrof !

### ISSUE THREAD

**Issue by TimGoulain** [TimGoulain/tim_app#23]
Jibai, help j'ai tout qui plante : j'ai essayé d'installer Mandrill et configurer l'envoi des emails, et j'ai du planter quelques trucs... Maintenant, quand je lance le serveur rails s et que j'essaye d'ouvrir localhost:4567, j'ai ce message qui apparait dans la console : 

```
[2015-09-15 13:12:43] ERROR bad Request-Line `\x16\x03\x01\x00▒\x01\x00\x00▒\x03\x03▒]▒▒\x03▒C\x14▒nY?f|{▒e▒d▒▒▒@F▒▒▒▒*▒R\x00\x00\x16▒+▒/▒'.
```

Et j'ai le message : "Echec de la connexion sécurisée" sur Firefox. J'ai essayé avec Chrome, ça ne marche pas non plus... 

Est-ce que je dois commiter et pusher pour te montrer ce que j'ai fait ? j'ai essayé de mettre les trucs en commentaires, mais ça ne marche pas non plus. A moins que le problème soit extérieur?

**Comment by TimGoulain** [comment]
NB : sur Chrome, ça me dit "Erreur de connexion SSL"

**Comment by TimGoulain** [comment]
punaise... https vs http ... 
N'en parlons plus  -_-'

**Comment by jibai31** [comment]
:-)
